esphome:
  name: $hostname
  comment: ${device_description}
  platform: ESP32
  board: esp32dev

substitutions:
  devicename: vogelhuis01
  hostname: "vogelhuis01"
  #friendly_name: 
  device_description: Vogelhuiscamera met sensors in notenboom
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: .lan

  # Optional manual IP
  manual_ip:
    static_ip: 192.168.1.100
    gateway: 192.168.1.1
    subnet: 255.255.255.0
    dns1: 192.168.1.1
    dns2: 8.8.8.8

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: “${devicename} Fallback AP"
    password: !secret fallback_ap_password

captive_portal:

# Enable logging
logger:
  level: warn

web_server:
  port: 80
  include_internal: true
  
# Enable Home Assistant API & OTA Updates
api:
 password: !secret api_password
 encryption:
  key:  !secret api_key_password
    
ota:
 password: !secret ota_password
 safe_mode: true
 reboot_timeout: 10min
 num_attempts: 5

time:
  - platform: homeassistant
    id: homeassistant_time

globals:
  - id: brightness_val
    type: int
    restore_value: true
    initial_value: '0'
    
    
    
# ESP32-CAM
esp32_camera:
  name: $hostname
 # id: camera1
  icon: mdi:bird
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  
  resolution: 800x600
  #resolution: 640x480
  jpeg_quality: 15
  aec_mode: auto
  aec2: true
  ae_level: 2
  brightness: 2
  #brightness_val
  contrast: 0
 # saturation: 1
  wb_mode: home  #cloudy,office

#  on_stream_start:
  #  - script.execute: open_flash_script


script:
  - id: open_flash_script
    mode: restart
    then:
      - if:
          condition:
            light.is_off: flashlight
          then:
            - light.turn_on: flashlight
      - delay: 3s
      - light.turn_off: flashlight

  
# Example configuration entry
esp32_camera_web_server:
  - port: 8080
    mode: stream
  - port: 8081
    mode: snapshot
    
# Flashlight
output:
  - platform: ledc
    pin: GPIO4
    id: gpio_4
    channel: 2

## GPIO_4 is the flash light pin
light:
  - platform: monochromatic
    id: flashlight
    output: gpio_4
    name: $hostname light
    restore_mode: RESTORE_AND_OFF
    icon: mdi:flash

dallas:
  - pin: GPIO13
    update_interval: 10s

sensor:
  - platform: dallas
    id: temperature1
    address: 0x7001186db7d0ff28
    name: "${hostname} temperature"    
    device_class: "temperature"
    state_class: "measurement"
    unit_of_measurement: "°C"
    filters:
      - sliding_window_moving_average:
          window_size: 10
          send_every: 10    
      - lambda:  return x * 0.7;

  - platform: uptime
    name: $hostname Uptime
    disabled_by_default: true
    entity_category: diagnostic  
    
  - platform: wifi_signal
    name: $hostname WiFi Signal
    update_interval: 240s
    disabled_by_default: true
    entity_category: diagnostic  


text_sensor:
  
  - platform: wifi_info
    ip_address:
      name: IP-adres
      id: ip_adres
      icon: mdi:ip-network
      
    ssid:
      name: Netwerk
      id: netwerk
      icon: mdi:access-point-network
      internal: true
    mac_address:
      name: Mac-adres
      id: mac_adres
      icon: mdi:folder-key-network-outline 
      internal: true

  - platform: version
    name: ESPHome Version
    hide_timestamp: true  
    internal: true

button:
  - platform: restart
    name: "${hostname} restart"   
    entity_category: config
